// Views
export 'splash/splash_view.dart';
export 'auth/auth_view.dart';
export 'dashboard/dashboard_view.dart';
export 'projects/projects_view.dart';
export 'camera/camera_view.dart';
export 'contacts/contacts_view.dart';
export 'highlights/highlights_view.dart';
export 'layout/main_layout.dart';
export 'zones/zones_view.dart';
export 'new_project/new_project_view.dart';
export 'room_adjust/room_adjust_view.dart';
export 'contact_details/contact_details_view.dart';
export 'overview_zones/overview_zones_view.dart';
export 'select_colors/select_colors_view.dart';
export 'new_contact/new_contact_view.dart';
